<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/users
spring.datasource.username=root
spring.datasource.password=sedhu1234
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&sslMode=REQUIRED
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.main.allow-bean-definition-overriding=true
>>>>>>> fa0b2ff3c1abd6d33ba3402e751bda2d5ae95d13
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}
